### PR TITLE
Configure action mailer

### PR DESCRIPTION
**Pull request by eleidan**

### CODE REVIEW

**Comment by rubycop** [comment]
Do not forget add tests for mailer

**Comment by eleidan** [comment]
Does it make sense to test features from a potentially well tested gem?

**Comment by rubycop** [comment]
You said about issues when app send email using yandex provider.

**Comment by eleidan** [comment]
I find it not feasible to test code I do not have access to, I mean code at Yandex. They can change theirs API any time they want. They can just close SMTP access etc.
Again, I see no good reason to test vendor provided code, at least in this case.

**Pull request merged**
